spring:
  application:
   name: jwt-auth
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

